onecrm/client/urls.py
from django.urls import path

from . import views
app_name = 'clients'

urlpatterns = [
    path('', views.clients_list, name='list'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/add-comment/', views.clients_detail, name= 'add_comment'),
    path('add/', views.clients_add, name='add'),
]

onecrm/dashboard/urls.py
from django.urls import path 

from . import views 

app_name = 'dashboard' 
urlpatterns = [
    path('', views.dashbaord , name= 'index'),
]

onecrm/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListview.as_view() , name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClient.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name= 'add_comment'),
    path('add/', views.LeadCreateView.as_view(), name='add' ),
]

onecrm/onecrm/urls.py
from django.contrib import admin
from django.contrib.auth import views 
from django.urls import path, include

from core.views import index, about


urlpatterns = [
    path('',index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('log-out/',views.LogoutView.as_view(), name='logout'),
    path("admin/", admin.site.urls),
]

onecrm/dashboard/models.py
from django.db import models

# Create your models here.

onecrm/lead/models.py
from django.contrib.auth.models import User
from django.db import models
from team.models import Team

class Lead(models.Model):

    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
        
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )
    
    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY , default = MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User , related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('name',)
    
    def __str__(self):
        return self.name
    
class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='lead_comments', on_delete=models.CASCADE)
    lead= models.ForeignKey(Lead, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User , related_name='lead_commnets', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.created_by.username

 

onecrm/dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from lead.models import Lead
from client.models import Client
from team.models import Team




@login_required
def dashbaord(request):
    team = Team.objects.filter(created_by=request.user)[0]
    leads = Lead.objects.filter(team=team, converted_to_client=False).order_by('-created_at')[0:5]
    clients = Client.objects.filter(team=team).order_by('-created_at')[0:5]
    return render(request, 'dashboard/dashboard.html',{
        'leads':leads,
        'clients': clients,
    })

onecrm/dashboard/templates/dashboard/dashboard.html
{% extends 'core/base.html' %}

{% block title %} Dashboard {% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class=" mb-6 text-xl"> Dashboard </h1>

    <div class="flex space-x-4">

        <div class="w-1/2 py-6 px-4 bg-yellow-500 rounded-xl leads">
            <h2 class="mb-2 text-lg font-bold"> Newest Leads</h2>
            {% for lead in leads %}
                <div class="mb-2 lead">
                    <h3 class="font-semibold">{{lead.name}}</h3>
                    <p class=""> Status: {{ lead.get_status_display}}</p>
                    <p class=""> Priority: {{ lead.get_priority_display}}</p>

                    <a href="{% url 'leads:detail' lead.pk %}">Details</a>
                </div>
            {% endfor %}
        </div>


        <div class="w-1/2 py-6 px-4 bg-yellow-500 rounded-xl clients">
            <h2 class="mb-2 text-lg font-bold"> Newest Clients</h2>

            {% for client in clients %}
                <div class="mb-2 client">
                    <h3 class="font-semibold">{{client.name}}</h3>

                    <a href="{% url 'clients:detail' client.pk %}">Details</a>
                </div>
            {% endfor %}
        </div>

    </div>
</div>
{% endblock %} 