onecrm/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListview.as_view() , name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClient.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name= 'add_comment'),
    path('add/', views.LeadCreateView.as_view(), name='add' ),
]

onecrm/onecrm/urls.py
from django.contrib import admin
from django.contrib.auth import views 
from django.urls import path, include

from core.views import index, about


urlpatterns = [
    path('',index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('log-out/',views.LogoutView.as_view(), name='logout'),
    path("admin/", admin.site.urls),
]

onecrm/lead/models.py
from django.contrib.auth.models import User
from django.db import models
from team.models import Team

class Lead(models.Model):

    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
        
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )
    
    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY , default = MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User , related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('name',)
    
    def __str__(self):
        return self.name
    
class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='lead_comments', on_delete=models.CASCADE)
    lead= models.ForeignKey(Lead, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User , related_name='lead_commnets', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.created_by.username

 

onecrm/lead/forms.py
from django import forms

from .models import Lead , Comment

class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead 
        fields = ('name', 'email', 'description', 'priority', 'status',)

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields=('content',)

onecrm/lead/views.py
from typing import Any, Dict, Optional
from django import http
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import models
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy  
from .forms import AddCommentForm
from .models import Lead
from client.models import Client , Comment as  ClinetComment
from team.models import Team
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from django.views.generic.edit import DeleteView
from django.views import View



class LeadListview(ListView):
    model = Lead
    
    @method_decorator (login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def get_queryset(self):
        queryset =  super(LeadListview, self).get_queryset()

        return queryset.filter(created_by=self.request.user, converted_to_client=False)
    

class LeadDetailView(DetailView):
    model = Lead

    @method_decorator (login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form']= AddCommentForm()
        return context 
    
    def get_queryset(self):
        queryset =  super(LeadDetailView, self).get_queryset()

        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))


class LeadDeleteView(DeleteView):
    model = Lead
    success_url = reverse_lazy('leads:list')
    
    @method_decorator (login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    

    def get_queryset(self):
        queryset =  super(LeadDeleteView, self).get_queryset()

        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))
    
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)
    


class LeadUpdateView(UpdateView):
    model = Lead
    fields = ('name', 'email', 'description', 'priority', 'status',)
    success_url = reverse_lazy('leads:list')

    @method_decorator (login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title']= 'Edit Lead'
        return context     
    
    
    def get_queryset(self):
        queryset =  super(LeadUpdateView, self).get_queryset()

        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))

    def form_valid(self, form):
        messages.success(self.request, "Lead has been updated successfully")
        return super().form_valid(form)


class LeadCreateView(CreateView):
    model = Lead
    fields = ('name', 'email', 'description', 'priority', 'status',)
    success_url = reverse_lazy('leads:list')


    @method_decorator (login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team = Team.objects.filter(created_by=self.request.user)[0]
        context['team']= team
        context['title']= 'Add Lead'
        return context 
    
    def form_valid(self,form):
        
        team = Team.objects.filter(created_by=self.request.user)[0]

        self.object = form.save(commit=False)
        self.object.created_by= self.request.user
        self.object.team = team 
        self.object.save()

        messages.success(self.request, "Lead has been added to the database succesfully")

        return redirect (self.get_success_url())

class AddCommentView(View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        form = AddCommentForm(request.POST)

        if form.is_valid():
            team = Team.objects.filter(created_by=request.user)[0]
            comment = form.save(commit=False )
            comment.team = team
            comment.created_by= request.user
            comment.lead_id=pk
            comment.save()

        return redirect('leads:detail', pk=pk  )

class ConvertToClient(View):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
        team = Team.objects.filter(created_by=request.user)[0]

        client = Client.objects.create(
            name = lead.name,
            email = lead.email,
            description = lead.description,
            created_by = request.user,
            team = team,
        )

    
        lead.converted_to_client = True
        lead.save()

    #convert leads comment to clienr comment
        comments = lead.comments.all()

        for comment in comments:
            ClinetComment.objects.create(
            client = client,
            content = comment.content,
            created_by = comment.created_by,
            team = team, 
        )

        messages.success(request, "Lead has been converted to client succesfully")

        return redirect('leads:list')

onecrm/lead/templates/lead/lead_detail.html
{% extends 'core/base.html' %}

{% block title %} {{lead.name}} {% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl"> {{lead.name}}  </h1>


        {% if lead.description %}
            <p class="font-semibold">Name</p>
            <p class="mb-2"> {{lead.description}} </p>
        {% endif %}

        <p class="font-semibold"> Priority </p>
        <p class="mb-2"> {{lead.get_priority_display}} </p>

        <p class="font-semibold"> Status </p>
        <p class="mb-2"> {{lead.get_status_display}} </p>

        <p class="font-semibold"> Created at </p>
        <p class="mb-2"> {{lead.created_at | date:"M-d-Y H:i" }} </p>

        <p class="font-semibold"> Modified at </p>
        <p class="mb-6"> {{lead.modified_at | date:"M-d-Y H:i"}} </p>

        

        <hr class="my-4">

            <form id="lead_delete_form" method="post" action="{% url 'leads:delete' lead.id %}">
                {% csrf_token %}
            </form>

            <a href="{% url 'leads:convert' lead.id %}" class="py-2 px-4 mr-2 bg-yellow-900 text-white">Convert to client</a>
            <a href="{% url 'leads:edit' lead.id %}" class="py-2 px-4 mr-2 bg-blue-900 text-white">Edit</a>
            <a href="{% url 'leads:delete' lead.id %}" onclick = "document.getElementById('lead_delete_form').submit();" class="py-2 px-4 mr-2 bg-red-600 ">Delete</a>
        
        <hr class="my-4">

            <h2 class="text-xl">Comments</h2>

            <div class="space-y-4">

                {% for comment in lead.comments.all %}
                    <div class="mb-2 bg-yellow-500 py-2 px-2 rounded-xl">
                        <p class="mb-2 ">
                            <strong>{{ comment.created_by }}</strong> @{{comment.created_at}}
                        </p>

                         {{ comment.content }}
                    </div>
                {% endfor %}

            </div>

                <form method="post" action="{% url 'leads:add_comment' lead.id %}">

                    {% csrf_token %}
                    {{ form.as_p }}
        
                    <button class="py-2 px-4 mr-2 bg-yellow-900 text-white">Submit</button>

                </form>
        
        <hr class="my-4">

        <a href="{% url 'leads:list' %}">Back to Leads</a>
    </div>
{% endblock %}

onecrm/lead/templates/lead/lead_form.html
{% extends 'core/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl"> {{ title }}  </h1>

        {% if team.plan.max_leads > team.leads.count or title == 'Edit Lead' %}

            <form method="post" action=".">
                {% csrf_token %}

                {{form.as_p}}

                <button class="py-4 px-8 bg-teal-900 text-white rounded-xl">Submit</button>
    
            </form>

        {% else %}
            <div class=" inline-block mt-6 px-6 py-6 bg-red-400 rounded-xl text-white">
                Your team have reached the max limit of you plan.
                Your owner must upgrade their current plan!
            </div>
        {% endif %}
    </div>
{% endblock %}

onecrm/lead/templates/lead/lead_list.html
{% extends 'core/base.html' %}

{% block title %} Leads {% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl"> Leads  </h1>

        <a href="{% url 'leads:add' %}" class="inline-block py-3 px-5 text-white bg-blue-900 rounded-xl"> Add Lead </a>


        {% if object_list  %}
            <div class="mt-6 mb-2 flex justify-between">
                <p class="py-4 px-2 bg-yellow-500 font-semibold w-full">Name</p>
                <p class="py-4 px-2 bg-yellow-500 font-semibold w-full">Priority</p>
                <p class="py-4 px-2 bg-yellow-500 font-semibold w-full">Status</p>
            </div>
            {% for lead in object_list %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full">
                        <a href="{% url 'leads:detail' lead.id %}">{{lead.name}} </a>
                    </p>
                    <p class="py-2 px-2 w-full"> {{lead.get_priority_display}} </p>
                    <p class="py-2 px-2 w-full"> {{lead.get_status_display}} </p>
                </div>
            {% endfor %}
        
        {% else %}
            <p class="px-2 mt-6 " > There are no leads available in the database </p>
        {% endif %}
    </div>
{% endblock  %}

onecrm/lead/templates/lead/leads_detail.html
{% extends 'core/base.html' %}

{% block title %} {{lead.name}} {% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl"> {{lead.name}}  </h1>


        {% if lead.description %}
            <p class="font-semibold">Name</p>
            <p class="mb-2"> {{lead.description}} </p>
        {% endif %}

        <p class="font-semibold"> Priority </p>
        <p class="mb-2"> {{lead.get_priority_display}} </p>

        <p class="font-semibold"> Status </p>
        <p class="mb-2"> {{lead.get_status_display}} </p>

        <p class="font-semibold"> Created at </p>
        <p class="mb-2"> {{lead.created_at | date:"M-d-Y H:i" }} </p>

        <p class="font-semibold"> Modified at </p>
        <p class="mb-6"> {{lead.modified_at | date:"M-d-Y H:i"}} </p>

        <hr class="my-4">
            <a href="{% url 'leads:convert' lead.id %}" class="py-2 px-4 mr-2 bg-yellow-900 text-white">Convert to client</a>
            <a href="{% url 'leads:edit' lead.id %}" class="py-2 px-4 mr-2 bg-blue-900 text-white">Edit</a>
            <a href="{% url 'leads:delete' lead.id %}" class="py-2 px-4 mr-2 bg-red-600 ">Delete</a>
        <hr class="my-4">

        <a href="{% url 'leads:list' %}">Back to Leads</a>
    </div>
{% endblock %}