onecrm/client/urls.py
from django.urls import path

from . import views
app_name = 'clients'

urlpatterns = [
    path('', views.clients_list, name='list'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/add-comment/', views.clients_detail, name= 'add_comment'),
    path('add/', views.clients_add, name='add'),
]

onecrm/dashboard/urls.py
from django.urls import path 

from . import views 

app_name = 'dashboard' 
urlpatterns = [
    path('', views.dashbaord , name= 'index'),
]

onecrm/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListview.as_view() , name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClient.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name= 'add_comment'),
    path('add/', views.LeadCreateView.as_view(), name='add' ),
]

onecrm/onecrm/urls.py
from django.contrib import admin
from django.contrib.auth import views 
from django.urls import path, include

from core.views import index, about


urlpatterns = [
    path('',index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('log-out/',views.LogoutView.as_view(), name='logout'),
    path("admin/", admin.site.urls),
]

onecrm/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('myaccount/', views.myaccount, name='myaccount'),
    path('sign-up/', views. signup, name = 'signup'),
]

onecrm/core/models.py
from django.db import models

# Create your models here.

onecrm/core/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request, 'core/about.html')

onecrm/core/templates/core/about.html
{% extends 'core/base.html' %}
{% block title %} 
ABOUT 
{% endblock %} 
{% block content %} 
This is the about 
{% endblock %}

onecrm/core/templates/core/base.html
{% load static %}
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'main.min.css' %}">

        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="py-6 px-6 flex justify-between bg-blue-500">
            <a href="/"class="text-bold text-white">ONECRM</a>

            <div class="space-x-3">
                <a href="{% url 'about' %}" class="text-white ">About</a>

                {% if request.user.is_authenticated %}
                    <a href="{% url 'dashboard:index' %}" class="text-white py-4 px-6 bg-blue-900 rounded-xl"> Dashboard </a>
                    <a href="{% url 'leads:list' %}" class="text-white py-4 px-6 bg-blue-900 rounded-xl"> Leads </a>
                    <a href="{% url 'clients:list' %}" class="text-white py-4 px-6 bg-blue-900 rounded-xl"> Clients </a>
                    <a href="{% url 'userprofile:myaccount' %}" class="text-white py-4 px-6 bg-blue-900 rounded-xl"> My Account </a>
                {% else %}
                    <a href="{% url 'userprofile:login' %}" class="text-white py-4 px-6 bg-blue-900 rounded-xl"> Log In </a>
                
                    <a href="{% url 'userprofile:signup' %}" class="text-white py-4 px-6 bg-blue-900 rounded-xl"> Sign Up </a>

                {% endif %}

                
            </div>

        </nav>

        {% if messages %}
            <div class="py-6 px-6">
                {% for message in messages %}
                    <div class="py-4 px-4 bg-red-400 rounded-xl">
                        {{message}}
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% block content %}
        {% endblock %}

        <footer class="py-7 text-center bg-gray-300">
            <p class="text-l"> © 2023 ONECRM | All rights reserved | Privacy Policy | Terms of Use </p>
        </footer>
    </body>
</html>

onecrm/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
ONECRM
{% endblock %}

{% block content %} 
    <div class="py-6 px-6">
        <h1 class="text-xl"> This is the Front Page </h1>
    </div>
{% endblock %}