onecrm/client/urls.py
from django.urls import path

from . import views
app_name = 'clients'

urlpatterns = [
    path('', views.clients_list, name='list'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/add-comment/', views.clients_detail, name= 'add_comment'),
    path('add/', views.clients_add, name='add'),
]

onecrm/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListview.as_view() , name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClient.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name= 'add_comment'),
    path('add/', views.LeadCreateView.as_view(), name='add' ),
]

onecrm/onecrm/urls.py
from django.contrib import admin
from django.contrib.auth import views 
from django.urls import path, include

from core.views import index, about


urlpatterns = [
    path('',index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('log-out/',views.LogoutView.as_view(), name='logout'),
    path("admin/", admin.site.urls),
]

onecrm/client/models.py
from django.contrib.auth.models import User
from django.db import models
from team.models import Team

class Client(models.Model):
    team = models.ForeignKey(Team, related_name='clients', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User , related_name='clients', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    

class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='client_comments', on_delete=models.CASCADE)
    client= models.ForeignKey(Client, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User , related_name='client_commnets', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.created_by.username

onecrm/client/forms.py
from django import forms

from .models import Client, Comment

class AddClientForm(forms.ModelForm):
    class Meta:
        model = Client 
        fields = ('name', 'email', 'description',)


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields=('content',)

onecrm/client/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .forms import AddClientForm,AddCommentForm
from .models import Client
from team.models import Team


@login_required
def clients_list(request):
    clients = Client.objects.filter(created_by=request.user)
    return render(request, 'client/clients_list.html',{
        'clients' : clients
    })

@login_required
def clients_detail(request, pk):
    client = get_object_or_404(Client, created_by = request.user, pk=pk)
    team = Team.objects.filter(created_by=request.user)[0]

    if request.method == 'POST':
        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = team 
            comment.created_by = request.user
            comment.client = client 
            comment.save()

            return redirect('clients:detail', pk=pk)

    else:
        form = AddCommentForm()


    return render(request, 'client/clients_detail.html',{
        'client' : client,
        'form' : form
    })



@login_required
def clients_add(request):
    team = Team.objects.filter(created_by=request.user)[0]
    if request.method == 'POST':
        form = AddClientForm(request.POST)

        if form.is_valid():
            team = Team.objects.filter(created_by=request.user)[0]
            client = form.save(commit=False)
            client.created_by = request.user
            client.team = team 
            client.save()
            messages.success(request, "Client has been created succesfully")

            return redirect('clients:list')
        

    else:
        form = AddClientForm()
    return render(request, 'client/clients_add.html',{
        'form' : form,
        'team' : team,
    })

@login_required
def clients_delete(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    client.delete()
    messages.success(request, "Client has been deleted succesfully")

    return redirect('clients:list')

@login_required
def clients_edit(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form=AddClientForm(request.POST, instance=client)

        if form.is_valid():
            form.save()

            messages.success(request, "Client has been edited succesfully")

            return redirect('clients:list')
        
    else:
        form = AddClientForm(instance=client)

    return render(request, 'client/clients_edit.html',{
        'form' : form
    })

onecrm/client/templates/client/clients_add.html
{% extends 'core/base.html' %}

{% block title %} Add Client {% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl"> Add Client  </h1>


        {% if team.plan.max_clients > team.clients.all|length %}

            <form method="post" action=".">
                {% csrf_token %}

                {{form.as_p}}

                <button class="py-4 px-8 bg-teal-900 text-white rounded-xl">Submit</button>
    
            </form>
        {% else %}
        <div class="inline-block mt-6 px-6 py-6 bg-red-400 rounded-xl text-white">
            Your team have reached the max limit of you plan.
            Your owner must upgrade their current plan!
        </div>
        {% endif %}
    </div>
{% endblock %}

onecrm/client/templates/client/clients_detail.html
{% extends 'core/base.html' %}

{% block title %} {{client.name}} {% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl"> {{client.name}}  </h1>


        {% if client.description %}
            <p class="font-semibold">Description</p>
            <p class="mb-2"> {{client.description}} </p>
        {% endif %}

        <p class="font-semibold"> Created at </p>
        <p class="mb-2"> {{client.created_at | date:"M-d-Y H:i" }} </p>

        <p class="font-semibold"> Modified at </p>
        <p class="mb-6"> {{client.modified_at | date:"M-d-Y H:i"}} </p>

        <hr class="my-4">

            <a href="{% url 'clients:edit' client.id %}" class="py-2 px-4 mr-2 bg-blue-900 text-white">Edit</a>
            <a href="{% url 'clients:delete' client.id %}" class="py-2 px-4 mr-2 bg-red-600 ">Delete</a>

        <hr class="my-4">

            <h2 class="text-xl">Comments</h2>

            <div class="space-y-4">

                {% for comment in client.comments.all %}
                    <div class="mb-2 bg-yellow-500 py-2 px-2 rounded-xl">
                        <p class="mb-2 ">
                            <strong>{{ comment.created_by }}</strong> @{{comment.created_at}}
                        </p>

                         {{ comment.content }}
                    </div>
                {% endfor %}

            </div>

                <form method="post" action="{% url 'clients:add_comment' client.id %}">

                    {% csrf_token %}
                    {{ form.as_p }}
        
                    <button class="py-2 px-4 mr-2 bg-yellow-900 text-white">Submit</button>

                </form>

        <hr class="my-4">

        <a href="{% url 'clients:list' %}">Back to Clients</a>
    </div>
{% endblock %}

onecrm/client/templates/client/clients_edit.html
{% extends 'core/base.html' %}

{% block title %} Edit Client {% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl"> Edit Client </h1>

        <form method="post" action=".">
            {% csrf_token %}

            {{form.as_p}}

            <button class="py-4 px-8 bg-teal-900 text-white rounded-xl">Submit</button>
 
        </form>
    </div>
{% endblock %}

onecrm/client/templates/client/clients_list.html
{% extends 'core/base.html' %}

{% block title %} Clients {% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl"> Clients </h1>

         <a href="{% url 'clients:add' %}" class="inline-block py-3 px-5 text-white bg-blue-900 rounded-xl"> Add Clients </a>


        {% if clients %}
            <div class="mt-6 mb-2 flex justify-between">
                <p class="py-4 px-2 bg-yellow-500 font-semibold w-full">Name</p>
            </div>
            {% for client in clients %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full">
                        <a href="{% url 'clients:detail' client.id %}">{{client.name}} </a>
                    </p>
                </div>
            {% endfor %}
        
        {% else %}
            <p class="px-2 mt-6 " > There are no clients available in the database </p>
        {% endif %}
    </div>
{% endblock  %}